### ISSUE TITLE
向一些 class 添加 toString 重写

### ISSUE THREAD

**Issue by SNWCreations** [SNWCreations/JKook#14]
如题，对一些存在于本项目的 class (而非 interface) 进行 toString 重写有助于开发时调试。
此 Issue 主要针对 snw.jkook.message.component 包下的实体类，以及少数夹杂在 snw.jkook.entity 包中的实体类。

**Comment by xiaoACE6716** [comment]
见 #15 。另外snw.jkook.entity下不全是interface么(

**Comment by SNWCreations** [comment]
> 见 #15 。另外snw.jkook.entity下不全是interface么(

在 snw.jkook.entity.channel 包的某个地方，为了表示权限覆写，我写了几个内部实体类。
