### ISSUE TITLE
支持文件消息吗

### ISSUE THREAD

**Issue by linglong233** [SNWCreations/JKook#18]

**Comment by SNWCreations** [comment]
支持。
snw.jkook.message.component.FileComponent。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月11日(周日) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SNWCreations/JKook] 支持文件消息吗 (Issue #18)

**Comment by linglong233** [comment]
好的，感谢
