### ISSUE TITLE
关于User类中的getIdentifyNumber()方法获取值的问题

### ISSUE THREAD

**Issue by A1LExX** [SNWCreations/JKook#19]
我在运行[JKookTutorial](https://github.com/SNWCreations/JKookTutorial)中[ch_4](https://github.com/SNWCreations/JKookTutorial/ch_4)的代码时发现当`getIdentifyNumber()`获取到的用户`identify_num`为0开头时，
比如我的alex#0011 会得到的结果是alex#11 根据文档显示`getIdentifyNumber()`方法返回的是int类型，所以这个问题解决了
我又翻了一下官方文档，发现官方接口返回的`identify_num`是`String`类型，所以想问这种返回类型会跟官方接口保持统一吗？

**Comment by SNWCreations** [comment]
应当和官方同步。这是设计漏洞，将在下一个 API Patch 版本中修复。
感谢反馈。

**Comment by SNWCreations** [comment]
暂时你可以使用这个工具方法纠正:
```java
public static String toIdentifyNum(int val) {
  String s = String.valueOf(val);
  if (s.length() < 4) {
    StringBuilder sb = new StringBuilder();
    int appendLength = 4 - s.length();
    for (int i = 1; i <= appendLength; i++) {
      sb.append("0");
    }
    sb.append(s);
    return sb.toString();
  }
  return s;
}
```

**Comment by A1LExX** [comment]
好的，感谢
