### ISSUE TITLE
给 Jkook API 教程部署 vitepress 文档服务

### ISSUE THREAD

**Issue by natholdallas** [SNWCreations/JKook#26]
建议夏夜可以把写的教程全部使用 vitepress 部署并移植 doc, 如果可以我可以献一份力 ?

**Comment by natholdallas** [comment]
如果同意的话, 你可以创建一个名为 <name>.github.io 的仓库, 把我拉至 contributes 中即可, 我负责把 jkook tutorial 中的文档全部布置好路由并且编写 github actions, vitepress 文档预览图可以参考
![image](https://github.com/SNWCreations/JKook/assets/109703293/9c40e8dd-d7c9-451b-8013-7480adcb2236)

**Comment by natholdallas** [comment]
部署服务完全由 github 托管, 不需要自己搭建服务器, 和 jkook toturial 仓库一样, 只是为了有更好的教程界面和开发引导

**Comment by SNWCreations** [comment]
可以，待我晚上回来处理
