### ISSUE TITLE
VoiceChannel缺少参数

### ISSUE THREAD

**Issue by cnluminous** [SNWCreations/JKook#27]
snw.jkook.entity.channel.VoiceChannel 缺少 limit_amount(目前仅可在创建时设置size) 和 password (仅有haspassword(),无setpassword)，无法修改语音频道最大人数和设置语音频道密码

**Comment by SNWCreations** [comment]
#28
SNWCreations/KookBC#78
processing

**Comment by SNWCreations** [comment]
try https://github.com/SNWCreations/KookBC/actions/runs/9074094135
with JKook API 0.52.0

**Comment by SNWCreations** [comment]
closing as stale!

**Comment by SNWCreations** [comment]
please reopen this if not resolved
