### ISSUE TITLE
添加新的接口允许外部扩展判断权限操作

### ISSUE THREAD

**Issue by xiaoACE6716** [SNWCreations/JKook#33]
## 您理解并明白，您确认此 Issue 符合下列要求:

1. 请求添加的功能是为了增强 **KookBC** 的能力，如可配置性。
2. 请求添加的功能 **不是对 JKook API 的功能扩充** ，如果是，请到 [JKook 仓库](https://github.com/SNWCreations/JKook) 提交 Issue ，而不是在这里提交。
3. 当您的 Issue 不满足上述要求或有其他合理原因时，您的 Issue 将被关闭。

## 您期望添加什么

如题

## 设计思路

类似 mc 的 [LuckPerms](https://luckperms.net/) 插件这种东西?

**Comment by huanmeng-qwq** [comment]
![4O)I15ET9P}N) F5K4B 70O_tmb](https://github.com/user-attachments/assets/4cdfc1cb-abce-4192-8f24-fd131982f76b)

**Comment by xiaoACE6716** [comment]
> ![4O)I15ET9P}N) F5K4B 70O_tmb](https://private-user-images.githubusercontent.com/49704373/363461443-4cdfc1cb-abce-4192-8f24-fd131982f76b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjk1OTQsIm5iZiI6MTcyNTE2OTI5NCwicGF0aCI6Ii80OTcwNDM3My8zNjM0NjE0NDMtNGNkZmMxY2ItYWJjZS00MTkyLThmMjQtZmQxMzE5ODJmNzZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA1NDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODkxNThlZWM5ZGNhZjg0MGEyMjViYjI0OWNlMTJiMDRhMGRmNTc5YTg2NzMwYTkzYTg5YjNlNzkyZjFhMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZIcdOsriG7E7uSq7Pt94915TANUUOU0-YGr9mDHsv6Q)

![image](https://github.com/user-attachments/assets/fe3b9535-4d84-4a56-94b6-8373011cb37f)

**Comment by huanmeng-qwq** [comment]
@SNWCreations 该需求是否合理？

**Comment by SNWCreations** [comment]
这不是 KOOK 标准 API 提供的，无论是 JKook 还是 KookBC 都不适合添加这个。
但是可以作为一个独立库开发。

**Comment by SNWCreations** [comment]
我个人推荐引入 LuckPerms 在 JKook 上的实现。

**Comment by huanmeng-qwq** [comment]
> 这不是 KOOK 标准 API 提供的，无论是 JKook 还是 KookBC 都不适合添加这个。 但是可以作为一个独立库开发。

本文中提到权限管理操作，由于JKook或KookBC并未开放接口接管权限判断

**Comment by SNWCreations** [comment]
我的个人建议是要求 KOOK 团队提供更简便的权限判断方法。
现有的方法极其繁琐，需要考虑频道上下文(UPO/RPO)，和用户本身拥有的角色。

**Comment by huanmeng-qwq** [comment]
JKook/KookBC是否应该提供一个接口允许外部扩展判断权限操作，而KOOK内部的权限判断则调用已实现的底层判断方法

**Comment by SNWCreations** [comment]
> JKook/KookBC是否应该提供一个接口允许外部扩展判断权限操作，而KOOK内部的权限判断则调用已实现的底层判断方法

这个可以，欢迎API PR

**Comment by SNWCreations** [comment]
Done
