### ISSUE TITLE
Where is the implementation of PluginManager?

### ISSUE THREAD

**Issue by zyklone4096** [SNWCreations/JKook#6]
where is your plugin manager, i cant find implementation of it

**Comment by SNWCreations** [comment]
You can just use it by using JKook.getPluginManager() in JKook plugins, and you can ignore the implementation.
If you want to see the implementation code, see SNWCreations/KookBC repository for more information.




夏夜之风
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SNWCreations/JKook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月19日(星期四) 晚上7:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SNWCreations/JKook] what (Issue #6)





 
where is your plugin manager, i cant find implementation of it
